### PR TITLE
Add support for NTSC modes

### PR DESCRIPTION
**Pull request by drothlis**

### CODE REVIEW

**Comment by wmanley** [comment]
Have you tried this? Because I haven't

**Comment by drothlis** [comment]
Not yet, I didn't mean to merge it yet, I just raised the pull request for visibility.

**Comment by drothlis** [comment]
With `tvservice -e "CEA 4"` I get this:

> Using pipeline videotestsrc is-live=true pattern=white ! video/x-raw,width=640,height=240,framerate=**60/1** ! timestampoverlay ! queue ! videoconvert ! mmalvideosink name=mmalsink

And with `tvservice -e "CEA 4" --ntsc` I get this:

> Using pipeline videotestsrc is-live=true pattern=white ! video/x-raw,width=640,height=240,framerate=**60000/1001** ! timestampoverlay ! queue ! videoconvert ! mmalvideosink name=mmalsink

So it seems to be working as intended.

**Comment by drothlis** [comment]
| rpi: 60fps | rpi: 59.94fps
--- | --- | ---
stb-tester ONE: 60fps |  | 
stb-tester ONE: 59.94fps |  |

**Pull request merged**
